"""change relation of artist-song

Revision ID: 69b8989382c0
Revises: ca1dede5fa4c
Create Date: 2024-05-14 15:46:55.554828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b8989382c0'
down_revision: Union[str, None] = 'ca1dede5fa4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_song',
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], )
    )
    op.drop_table('song_artist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_artist',
    sa.Column('song_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name='song_artist_artist_id_fkey'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name='song_artist_song_id_fkey'),
    sa.PrimaryKeyConstraint('song_id', 'artist_id', name='song_artist_pkey')
    )
    op.drop_table('artist_song')
    # ### end Alembic commands ###
