"""change relation of artist-song

Revision ID: fb4afc0f174c
Revises: 69b8989382c0
Create Date: 2024-05-14 15:48:44.463179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb4afc0f174c'
down_revision: Union[str, None] = '69b8989382c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('songs_artist_id_fkey', 'songs', type_='foreignkey')
    op.drop_column('songs', 'artist_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('songs_artist_id_fkey', 'songs', 'artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###
